
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MC.Core.Dal
{

using System;
    using System.Collections.Generic;
    
public partial class Client
{

    public Client()
    {

        this.Properties = new HashSet<Property>();

    }


    public System.Guid Id { get; set; }

    public string AccountNumber { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string LoginName { get; set; }

    public string Password { get; set; }



    public virtual ICollection<Property> Properties { get; set; }

}

}
